### ISSUE TITLE
RTX 5090+CUDA 12.8+pytorch 2.7.1 install Mamba

### ISSUE THREAD

**Issue by naruto110** [state-spaces/mamba#745]
export CC=gcc-11
export CXX=g++-11
export CUDA_HOME=/usr/local/cuda-12.8
export TORCH_CUDA_ARCH_LIST="12.0"
git clone https://github.com/state-spaces/mamba.git
cd mamba
modify setup.py line 193 to “ cc_flag.append("arch=compute_120,code=sm_120") ”
pip install -e .
python -c "from mamba_ssm import Mamba; print('✅ Mamba imported successfully')"

**Comment by a1473838623** [comment]
This works for me. Thanks.
And [causal-conv1d](https://github.com/Dao-AILab/causal-conv1d) can be installed in the same way (except changing from "pip install -e ." to "pip install .").

**Comment by DAnonyvinciT** [comment]
This method worked for me and I successfully imported the package, but I encountered another issue when using it.

  File "/mnt/d/AcSuppot/mamba/mamba_ssm/ops/triton/ssd_combined.py", line 792, in forward
    causal_conv1d_fwd_function(rearrange_and_update_stride(xBC, "b s d -> b d s"),
TypeError: 'NoneType' object is not callable

It seems a triton issue

**Comment by DAnonyvinciT** [comment]
> This method worked for me and I successfully imported the package, but I encountered another issue when using it.
> 
> File "/mnt/d/AcSuppot/mamba/mamba_ssm/ops/triton/ssd_combined.py", line 792, in forward causal_conv1d_fwd_function(rearrange_and_update_stride(xBC, "b s d -> b d s"), TypeError: 'NoneType' object is not callable
> 
> It seems a triton issue



The issue has been resolved. The reason was that I didn't install causal-conv1d correctly.

**Comment by WiiliamC** [comment]
> export CC=gcc-11 export CXX=g++-11 export CUDA_HOME=/usr/local/cuda-12.8 export TORCH_CUDA_ARCH_LIST="12.0" git clone https://github.com/state-spaces/mamba.git cd mamba modify setup.py line 193 to “ cc_flag.append("arch=compute_120,code=sm_120") ” pip install -e . python -c "from mamba_ssm import Mamba; print('✅ Mamba imported successfully')"

Saved my day, naruto!

**Comment by WiiliamC** [comment]
BTW, set MAX_JOBS=N can speed up the compilation

**Comment by RangXuan** [comment]
it works to me ,thx

**Comment by wengmaochi** [comment]
@DAnonyvinciT Hi, I am also facing the same NoneType object issue as you did. I built causal-conv1d from source code, but I still get the same issue. Could you tell me what version of pytorch, cuda, causal-conv1d are you using? 
I am using python=3.12, pytorch=2.2.2, cuda=11.8. 
Thank you!

**Comment by psh9002** [comment]
Thanks a lot!!!!
In my case, RTX 4090+CUDA 12.8+pytorch 2.7.0(matched with CUDA version) and python=3.11
I also install with `pip install -e . --no-build-isolation`.
